title: Sakar Shrestha
logo: Assets/Icon photo.jpeg
description: Excel(VBA, Macros and Office Script), MySQL, Alteryx, Power BI, Python (Pandas, Numpy, Matplotlib)
show_downloads: true
theme: jekyll-theme-minimal

